"""
Program Name: team_codes
By: Omer Alon
Date: 15/04/17
Program Version: 1.0.0
"""


# Fit the team names in the two information sources
TEAMS_DICT = {"AFC Bournemouth": "AFC Bournemouth",
              "Arsenal FC": "Arsenal",
              "Burnley FC": "Burnley",
              "Chelsea FC": "Chelsea",
              "Crystal Palace FC": "Crystal Palace",
              "Everton FC": "Everton",
              "Hull City FC": "Hull City",
              "Leicester City FC": "Leicester City",
              "Liverpool FC": "Liverpool",
              "Manchester City FC": "Manchester City",
              "Manchester United FC": "Manchester United",
              "Middlesbrough FC": "Middlesbrough",
              "Southampton FC": "Southampton",
              "Stoke City FC": "Stoke City",
              "Sunderland AFC": "Sunderland",
              "Swansea City FC": "Swansea City",
              "Tottenham Hotspur FC": "Tottenham Hotspur",
              "Watford FC": "Watford",
              "West Bromwich Albion FC": "West Bromwich Albion",
              "West Ham United FC": "West Ham United",
              "Bayer Leverkusen": "Bayer Leverkusen",
              "Borussia Dortmund": "Borussia Dortmund",
              u"Bor. M\xf6nchengladbach": "Borussia Monchengladbach",
              "Eintracht Frankfurt": "Eintracht Frankfurt",
              "FC Augsburg": "FC Augsburg",
              u"FC Bayern M\xfcnchen": "Bayern Munich",
              "FC Schalke 04": "Schalke 04",
              "FC Ingolstadt 04": "FC Ingolstadt 04",
              u"1. FC K\xf6ln": "FC Cologne",
              "1. FSV Mainz 05": "Mainz",
              "Hamburger SV": "Hamburg SV",
              "Hertha BSC": "Hertha Berlin",
              "Red Bull Leipzig": "RB Leipzig",
              "SC Freiburg": "SC Freiburg",
              "SV Darmstadt 98": "SV Darmstadt 98",
              "TSG 1899 Hoffenheim": "TSG Hoffenheim",
              "VfL Wolfsburg": "VfL Wolfsburg",
              "Werder Bremen": "Werder Bremen",
              u"SpVgg Greuther F\xfcrth": "SpVgg Greuther Furth",
              u'1. FC N\xfcrnberg': "Nurnberg",
              "Angers SCO": "Angers",
              "AS Monaco FC": "AS Monaco",
              "AS Nancy": "AS Nancy Lorraine",
              u"AS Saint-\xc9tienne": "St Etienne",
              "Dijon FCO": "Dijon FCO",
              "EA Guingamp": "Guingamp",
              "FC Girondins de Bordeaux": "Bordeaux",
              "FC Lorient": "Lorient",
              "FC Metz": "Metz",
              "FC Nantes": "Nantes",
              u"Montpellier H\xe9rault SC": "Montpellier",
              "OGC Nice": "Nice",
              "Olympique de Marseille": "Marseille",
              "Olympique Lyonnais": "Lyon",
              "OSC Lille": "Lille",
              "Paris Saint-Germain": "Paris Saint-Germain",
              "SC Bastia": "Bastia",
              "SM Caen": "Caen",
              "Stade Rennais FC": "Stade Rennes",
              "Toulouse FC": "Toulouse",
              "Athletic Club": "Athletic Bilbao",
              "CA Osasuna": "Osasuna",
              "CD Leganes": "Leganes",
              u"Club Atl\xe9tico de Madrid": "Atletico Madrid",
              u"Deportivo Alav\xe9s": "Alav\u00e9s",
              "FC Barcelona": "Barcelona",
              "Granada CF": "Granada",
              u"M\xe1laga CF": "M\xc3\xa1laga",
              "RC Celta de Vigo": "Celta Vigo",
              "RC Deportivo La Coruna": "Deportivo La Coru\u00f1a",
              "RCD Espanyol": "Espanyol",
              "Real Betis": "Real Betis",
              "Real Madrid CF": "Real Madrid",
              u"Real Sociedad de F\xfatbol": "Real Sociedad",
              "SD Eibar": "Eibar",
              "Sevilla FC": "Sevilla FC",
              u"Sporting Gij\xf3n": "Sporting Gij\xc3\xb3n",
              "UD Las Palmas": "Las Palmas",
              "Valencia CF": "Valencia",
              "Villarreal CF": "Villarreal",
              "AC Chievo Verona": "Chievo Verona",
              "ACF Fiorentina": "Fiorentina",
              "AC Milan": "AC Milan",
              "AS Roma": "AS Roma",
              "Atalanta BC": "Atalanta",
              "Bologna FC": "Bologna",
              "Cagliari Calcio": "Cagliari",
              "Empoli FC": "Empoli",
              "FC Crotone": "Crotone",
              "FC Internazionale Milano": "Internazionale",
              "Genoa CFC": "Genoa",
              "Juventus Turin": "Juventus",
              "Pescara Calcio": "US Pescara",
              "SSC Napoli": "Napoli",
              "SS Lazio": "Lazio",
              "Torino FC": "Torino",
              "UC Sampdoria": "Sampdoria",
              "Udinese Calcio": "Udinese",
              u'US Citt\xe1 di Palermo': "Palermo",
              "US Sassuolo Calcio": "Sassuolo"}
# Information server URL codes
TEAM_CODES = {"VfL Wolfsburg": 11,
              "Borussia Dortmund": 4,
              "FC Augsburg": 16,
              "TSG Hoffenheim": 2,
              "Hamburg SV": 7,
              "Bayer Leverkusen": 3,
              "Schalke 04": 6,
              "Mainz": 15,
              "Eintracht Frankfurt": 19,
              "SC Freiburg": 17,
              "Hertha Berlin": 9,
              "FC Ingolstadt 04": 31,
              "Werder Bremen": 12,
              "Swansea City": 72,
              "Osasuna": 79,
              "Real Betis": 90,
              "Arsenal": 57,
              "Granada": 83,
              "Athletic Bilbao": 77,
              "Barcelona": 81,
              "Valencia": 95,
              "Manchester United": 66,
              "Villarreal": 94,
              "Everton": 62,
              "AC Milan": 98,
              "SV Darmstadt 98": 55,
              "Manchester City": 65,
              "Fiorentina": 99,
              "Espanyol": 80,
              "Liverpool": 64,
              "Real Madrid": 86,
              "Tottenham Hotspur": 73,
              "Stoke City": 70,
              "Sunderland": 71,
              "West Bromwich Albion": 74,
              "Chelsea": 61,
              "AS Roma": 100,
              "Cagliari": 104,
              "Bologna": 103,
              "Atalanta": 102,
              "Genoa": 107,
              "Juventus": 109,
              "Chievo Verona": 106,
              "Napoli": 113,
              "Internazionale": 108,
              "Udinese": 115,
              "Lazio": 110,
              "Las Palmas": 275,
              "Eibar": 278,
              "Middlesbrough": 343,
              "Burnley": 328,
              "Watford": 346,
              "Leicester City": 338,
              "Southampton": 340,
              "Hull City": 322,
              "Crystal Palace": 354,
              "Empoli": 445,
              "Crotone": 472,
              "Sassuolo": 471,
              "Metz": 545,
              "AS Monaco": 548,
              "Nantes": 543,
              "Lyon": 523,
              "Lille": 521,
              "Dijon FCO": 528,
              "Lorient": 525,
              "AS Nancy Lorraine": 520,
              "Marseille": 516,
              "Paris Saint-Germain": 524,
              "Caen": 514,
              "Guingamp": 538,
              "Stade Rennais": 529,
              "Bordeaux": 526,
              "Toulouse": 511,
              "Angers": 532,
              "Nice": 522,
              "Bastia": 536,
              "Celta Vigo": 558,
              "US Pescara": 585,
              "Sevilla FC": 559,
              "Deportivo La Coru\u00f1a": 560,
              "Sampdoria": 584, None: 592,
              "Torino": 586,
              "West Ham United": 563,
              "Leganes": 745,
              "RB Leipzig": 721,
              "AFC Bournemouth": 1044,
              "Borussia Monchengladbach": 18,
              "Bayern Munich": 5,
              "FC Cologne": 1,
              "St Etienne": 527,
              "Montpellier": 518,
              "Atletico Madrid": 78,
              "M\xc3\xa1laga": 84,
              "Real Sociedad": 92,
              "Palermo": 114,
              "Alav\u00e9s": 263,
              "Sporting Gij\xc3\xb3n": 96}
# in case they change the names in the API
HOME = "homeTeamName"
AWAY = "awayTeamName"
HOME_GOALS = "goalsHomeTeam"
AWAY_GOALS = "goalsAwayTeam"
DATE = "date"
TIME = "time"
MATCHES = "games"
FINAL_TIME = "FT"
