"""TEAM_CODES = {'Swansea City FC': 72, 'SD Eibar': 278, 'UD Almeria': 267, 'SV Sandhausen': 46,
              'Paris Saint-Germain': 524, 'C\xc3\xb3rdoba CF': 295, 'RCD Espanyol': 80, '1. FC K\xc3\xb6ln': 1,
              'Athletic Club': 77, 'AS Monaco FC': 548, 'Manchester United FC': 66, 'Eintracht Frankfurt': 19,
              'Villarreal CF': 94, 'FC Porto': 503, 'Rayo Vallecano de Madrid': 87, 'Manchester City FC': 65,
              'Genoa CFC': 107, 'Hannover 96': 8, 'Leicester City FC': 338, 'AS Saint-\xc3\x89tienne': 527,
              'Liverpool FC': 64, 'Real Madrid CF': 86, 'Tottenham Hotspur FC': 73, 'Olympique Lyonnais': 523,
              'Fortuna D\xc3\xbcsseldorf': 24, 'PSV Eindhoven': 674, 'FC Schalke 04': 6, 'Sporting CP': 498,
              'Paris FC': 1045, 'Torino FC': 586, 'FC Girondins de Bordeaux': 526, 'Montpellier H\xc3\xa9rault SC': 518,
              'Werder Bremen': 12, 'US Sassuolo Calcio': 471, 'SL Benfica': 495, 'Red Bull Leipzig': 721,
              'Watford FC': 346, 'Karlsruher SC': 32, 'FC Lorient': 525, '1. FC Kaiserslautern': 13, 'Valencia CF': 95,
              'FSV Frankfurt': 30, 'Bayer Leverkusen': 3, 'FC Bayern M\xc3\xbcnchen': 5, '1. FC Heidenheim 1846': 44,
              'Granada CF': 83, '\xc3\x89vian Thonon Gaillard FC': 513, 'FC Nantes': 543, 'FC Augsburg': 16,
              'FC Barcelona': 81, 'RC Lens': 546, 'Eintracht Braunschweig': 33, '1. FC Union Berlin': 28,
              'Club Atl\xc3\xa9tico de Madrid': 78, 'Hertha BSC': 9, 'Juventus Turin': 109, 'Sunderland AFC': 71,
              'Olympique de Marseille': 516, 'West Bromwich Albion FC': 74, 'Toulouse FC': 511, 'Elche FC': 285,
              'RC Deportivo La Coruna': 560, 'Getafe CF': 82, 'SM Caen': 514, 'EA Guingamp': 538, 'OGC Nice': 522,
              'AC Milan': 98, 'VfL Wolfsburg': 11, 'Stade de Reims': 547, 'SC Paderborn 07': 29, 'Norwich City FC': 68,
              'FC Internazionale Milano': 108, 'Real Sociedad de F\xc3\xbatbol': 92, 'US Citt\xc3\xa1 di Palermo': 114,
              'Everton FC': 62, '1. FC N\xc3\xbcrnberg': 14, 'SV Darmstadt 98': 55, 'AS Roma': 100, 'VfR Aalen': 50,
              'ACF Fiorentina': 99, 'SpVgg Greuther F\xc3\xbcrth': 21, 'VfL Bochum': 36, 'FC Ingolstadt 04': 31,
              'FC Metz': 545, 'RC Celta de Vigo': 558, 'Hamburger SV': 7, 'Chelsea FC': 61, 'West Ham United FC': 563,
              'Aston Villa FC': 58, 'Crystal Palace FC': 354, 'Stade Rennais FC': 529, 'SS Lazio': 110,
              'VfB Stuttgart': 10, 'SC Bastia': 536, 'Erzgebirge Aue': 22, 'Borussia Dortmund': 4, 'SC Freiburg': 17,
              'Arsenal FC': 57, 'Sheffield United FC': 356, 'OSC Lille': 521, 'Levante UD': 88, '\xef\xbb\xbfAFC Bournemouth': 1044,
              'TSG 1899 Hoffenheim': 2, 'M\xc3\xa1laga CF': 84, 'Sevilla FC': 559, 'Bor. M\xc3\xb6nchengladbach': 18,
              '1. FSV Mainz 05': 15, 'SSC Napoli': 113, 'Empoli FC': 445, 'Stoke City FC': 70, 'FC St. Pauli': 20,
              'Newcastle United FC': 67, 'Southampton FC': 340}
"""
TEAM_CODES_NEW = {'VfL Wolfsburg': 11,
                  'Borussia Dortmund': 4,
                  'FC Augsburg': 16,
                  'TSG 1899 Hoffenheim': 2,
                  'Hamburger SV': 7,
                  'Bayer Leverkusen': 3,
                  'FC Schalke 04': 6,
                  '1. FSV Mainz 05': 15,
                  'Eintracht Frankfurt': 19,
                  'SC Freiburg': 17,
                  'Hertha BSC': 9,
                  'FC Ingolstadt 04': 31,
                  'Werder Bremen': 12,
                  'Swansea City FC': 72,
                  'CA Osasuna': 79,
                  'Real Betis': 90,
                  'Arsenal FC': 57,
                  'Granada CF': 83,
                  'Athletic Club': 77,
                  'FC Barcelona': 81,
                  'Valencia CF': 95,
                  'Manchester United FC': 66,
                  'Villarreal CF': 94,
                  'Everton FC': 62,
                  'AC Milan': 98,
                  'SV Darmstadt 98': 55,
                  'Manchester City FC': 65,
                  'ACF Fiorentina': 99,
                  'RCD Espanyol': 80,
                  'Liverpool FC': 64,
                  'Real Madrid CF': 86,
                  'Tottenham Hotspur FC': 73,
                  'Stoke City FC': 70,
                  'Sunderland AFC': 71,
                  'West Bromwich Albion FC': 74,
                  'Chelsea FC': 61,
                  'AS Roma': 100,
                  'Cagliari Calcio': 104,
                  'Bologna FC': 103,
                  'Atalanta BC': 102,
                  'Genoa CFC': 107,
                  'Juventus Turin': 109,
                  'AC Chievo Verona': 106,
                  'SSC Napoli': 113,
                  'FC Internazionale Milano': 108,
                  'Udinese Calcio': 115,
                  'SS Lazio': 110,
                  'UD Las Palmas': 275,
                  'SD Eibar': 278,
                  'Middlesbrough FC': 343,
                  'Burnley FC': 328,
                  'Watford FC': 346,
                  'Leicester City FC': 338,
                  'Southampton FC': 340,
                  'Hull City FC': 322,
                  'Crystal Palace FC': 354,
                  'Empoli FC': 445,
                  'FC Crotone': 472,
                  'US Sassuolo Calcio': 471,
                  'FC Metz': 545,
                  'AS Monaco FC': 548,
                  'FC Nantes': 543,
                  'Olympique Lyonnais': 523,
                  'OSC Lille': 521,
                  'Dijon FCO': 528,
                  'FC Lorient': 525,
                  'AS Nancy': 520,
                  'Olympique de Marseille': 516,
                  'Paris Saint-Germain': 524,
                  'SM Caen': 514,
                  'EA Guingamp': 538,
                  'Stade Rennais FC': 529,
                  'FC Girondins de Bordeaux': 526,
                  'Toulouse FC': 511,
                  'Angers SCO': 532,
                  'OGC Nice': 522,
                  'SC Bastia': 536,
                  'RC Celta de Vigo': 558,
                  'Pescara Calcio': 585,
                  'Sevilla FC': 559,
                  'RC Deportivo La Coruna': 560,
                  'UC Sampdoria': 584, None: 592,
                  'Torino FC': 586,
                  'West Ham United FC': 563,
                  'CD Leganes': 745,
                  'Red Bull Leipzig': 721,
                  '\xef\xbb\xbf\xef\xbb\xbfAFC Bournemouth': 1044,
                  'Bor. M\xc3\xb6nchengladbach': 18,
                  'FC Bayern M\xc3\xbcnchen': 5,
                  '1. FC K\xc3\xb6ln': 1,
                  'AS Saint-\xc3\x89tienne': 527,
                  'Montpellier H\xc3\xa9rault SC': 518,
                  'Club Atl\xc3\xa9tico de Madrid': 78,
                  'M\xc3\xa1laga CF': 84,
                  'Real Sociedad de F\xc3\xbatbol': 92,
                  'US Citt\xc3\xa1 di Palermo': 114,
                  'Deportivo Alav\xc3\xa9s': 263,
                  'Sporting Gij\xc3\xb3n': 96}